name: CI-windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:         
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Esy setup
        run: |
          bash -c build-windows.sh
          
