name: CI-windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:         
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Esy setup
        run: |
          #          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          npm install -g esy@latest
          esy install
          
